# Generated by Django 5.2.15 on 2026-06-13 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('administrative', 'Administrative'), ('hostel', 'Hostel'), ('facility', 'Facility'), ('religious', 'Religious'), ('sport', 'Sport'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_accessible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_as_destination', to='navigation.building')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_as_origin', to='navigation.building')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('waypoint_type', models.CharField(choices=[('entrance', 'Building Entrance'), ('junction', 'Pathway Junction'), ('parking', 'Parking Area'), ('landmark', 'Landmark')], default='junction', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoints', to='navigation.building')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in meters')),
                ('surface', models.CharField(choices=[('footpath', 'Footpath'), ('road', 'Road'), ('indoor', 'Indoor Corridor')], default='footpath', max_length=20)),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible')),
                ('is_active', models.BooleanField(default=True)),
                ('from_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='navigation.waypoint')),
                ('to_waypoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='navigation.waypoint')),
            ],
            options={
                'unique_together': {('from_waypoint', 'to_waypoint')},
            },
        ),
    ]
